/**
 * VaultClient — typed SDK for vault-service membership operations (VLT-7 US-001).
 *
 * Wraps vault-service HTTP API with shared auth, retry, and typed errors.
 * Colocated with hq-cloud so /invite, /promote, /accept and future commands
 * share one client instead of each rolling its own HTTP layer.
 */

import type { VaultServiceConfig } from "./types.js";

// ---------------------------------------------------------------------------
// Error classes
// ---------------------------------------------------------------------------

export class VaultClientError extends Error {
  constructor(
    message: string,
    public readonly statusCode: number,
    public readonly body?: string,
  ) {
    super(message);
    this.name = "VaultClientError";
  }
}

export class VaultAuthError extends VaultClientError {
  constructor(message = "Authentication failed — session expired or invalid") {
    super(message, 401);
    this.name = "VaultAuthError";
  }
}

export class VaultPermissionDeniedError extends VaultClientError {
  constructor(message = "Permission denied — admin role required") {
    super(message, 403);
    this.name = "VaultPermissionDeniedError";
  }
}

export class VaultNotFoundError extends VaultClientError {
  constructor(message = "Resource not found") {
    super(message, 404);
    this.name = "VaultNotFoundError";
  }
}

export class VaultConflictError extends VaultClientError {
  constructor(message = "Conflict — resource already exists or was already accepted") {
    super(message, 409);
    this.name = "VaultConflictError";
  }
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type MembershipRole = "owner" | "admin" | "member" | "guest";
export type MembershipStatus = "pending" | "active" | "revoked";

export interface Membership {
  membershipKey: string;
  personUid: string;
  companyUid: string;
  role: MembershipRole;
  status: MembershipStatus;
  allowedPrefixes?: string[];
  inviteToken?: string;
  invitedBy: string;
  invitedAt: string;
  acceptedAt?: string;
  revokedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateInviteInput {
  personUid?: string;
  inviteeEmail?: string;
  companyUid: string;
  role: MembershipRole;
  allowedPrefixes?: string[];
  invitedBy: string;
}

export interface CreateInviteResult {
  membership: Membership;
  inviteToken: string;
}

export interface AcceptInviteResult {
  membership: Membership;
}

export interface UpdateRoleInput {
  membershipKey: string;
  newRole: MembershipRole;
  allowedPrefixes?: string[];
  updaterUid: string;
  /** Required so the server can authorize the caller as admin/owner of the company. */
  companyUid: string;
}

export interface EntityInfo {
  uid: string;
  slug: string;
  type: string;
  bucketName?: string;
  status: string;
}

export interface CreateEntityInput {
  type: "person" | "company";
  slug: string;
  name: string;
  email?: string;
  ownerUid?: string;
}

export interface CreateEntityResult {
  entity: EntityInfo;
}

// -- STS child vending (VLT-8) --------------------------------------------

export type TaskAction = "read" | "write";

export interface TaskScope {
  /** S3 key prefixes the child may access (e.g. ["drafts/"]). */
  allowedPrefixes: string[];
  /** Defaults to ["read", "write"]. Use ["read"] for read-only children. */
  allowedActions?: TaskAction[];
}

export interface VendChildInput {
  companyUid: string;
  /** ULID generated by the parent task. Flows into STS session name for audit. */
  taskId: string;
  /** Short human-readable description (<256 chars). Logged alongside the session. */
  taskDescription: string;
  taskScope: TaskScope;
  /**
   * Child session duration in seconds. Defaults to 900 on the server — AWS STS
   * AssumeRole enforces a 900s floor. The task-scoped policy is the security
   * boundary, not the duration.
   */
  durationSeconds?: number;
}

export interface StsChildCredentials {
  accessKeyId: string;
  secretAccessKey: string;
  sessionToken: string;
}

export interface VendChildResult {
  credentials: StsChildCredentials;
  /** STS session name: `${parentPersonUid}--task--${taskId}` — used in CloudTrail.
   *  (Dash-separated because AWS STS `roleSessionName` disallows colons.) */
  sessionName: string;
  /** ISO-8601 session expiration. */
  expiresAt: string;
}

// ---------------------------------------------------------------------------
// Retry config
// ---------------------------------------------------------------------------

const MAX_RETRIES = 3;
const BASE_DELAY_MS = 500;

function isTransient(status: number): boolean {
  return status === 429 || status >= 500;
}

async function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// ---------------------------------------------------------------------------
// VaultClient
// ---------------------------------------------------------------------------

export class VaultClient {
  private readonly apiUrl: string;
  private readonly authToken: string;

  constructor(config: VaultServiceConfig) {
    this.apiUrl = config.apiUrl.replace(/\/+$/, "");
    this.authToken = config.authToken;
  }

  // -- Membership operations ------------------------------------------------

  async createInvite(input: CreateInviteInput): Promise<CreateInviteResult> {
    const data = await this.post<{ membership: Membership; inviteToken: string }>(
      "/membership/invite",
      input,
    );
    return data;
  }

  async acceptInvite(token: string, personUid: string): Promise<AcceptInviteResult> {
    const data = await this.post<{ membership: Membership }>(
      "/membership/accept",
      { token, personUid },
    );
    return data;
  }

  /**
   * Revoke a membership. The handler needs both the membershipKey AND the
   * companyUid so it can authorize the caller as admin/owner of the company
   * before performing the revoke. (We can't infer companyUid from the key
   * alone without an extra DDB read, and the caller already knows it.)
   */
  async revokeMembership(membershipKey: string, companyUid: string): Promise<void> {
    await this.post("/membership/revoke", { membershipKey, companyUid });
  }

  /**
   * List the caller's own active memberships.
   *
   * Server infers the caller's identity from the Cognito JWT `sub` claim and
   * returns the union of active memberships across every person entity owned
   * by that sub (orphan-tolerant — prior failed provisioning runs can leave
   * multiple `prs_*` rows for the same Cognito identity).
   *
   * Returns `[]` — NOT a 404 — when the caller has no person entity yet.
   * This lets `hq-sync-runner` distinguish "signed in but not bootstrapped"
   * (empty array → emit `setup-needed`) from "auth broken" (throws
   * VaultAuthError) without catching HTTP errors for flow control.
   *
   * Backed by `GET /membership/me` (see hq-pro ADR-0002).
   */
  async listMyMemberships(): Promise<Membership[]> {
    const data = await this.get<{ memberships: Membership[] }>("/membership/me");
    return data.memberships;
  }

  async listMembersOfCompany(companyUid: string): Promise<Membership[]> {
    const data = await this.get<{ members: Membership[] }>(
      `/membership/company/${encodeURIComponent(companyUid)}`,
    );
    return data.members;
  }

  async updateRole(input: UpdateRoleInput): Promise<Membership> {
    const data = await this.post<{ membership: Membership }>(
      "/membership/role",
      input,
    );
    return data.membership;
  }

  async listPendingInvites(companyUid: string): Promise<Membership[]> {
    const data = await this.get<{ invites: Membership[] }>(
      `/membership/company/${encodeURIComponent(companyUid)}/pending`,
    );
    return data.invites;
  }

  // -- Entity operations ----------------------------------------------------

  readonly entity = {
    get: async (uid: string): Promise<EntityInfo> => {
      const data = await this.get<{ entity: EntityInfo }>(`/entity/${encodeURIComponent(uid)}`);
      return data.entity;
    },

    findBySlug: async (type: string, slug: string): Promise<EntityInfo> => {
      const data = await this.get<{ entity: EntityInfo }>(
        `/entity/by-slug/${encodeURIComponent(type)}/${encodeURIComponent(slug)}`,
      );
      return data.entity;
    },

    create: async (input: CreateEntityInput): Promise<EntityInfo> => {
      const data = await this.post<CreateEntityResult>("/entity", input);
      return data.entity;
    },
  };

  // -- Provisioning operations (VLT-2) -----------------------------------------

  async provisionBucket(companyUid: string): Promise<{ bucketName: string; kmsKeyId: string }> {
    const data = await this.post<{ bucketName: string; kmsKeyId: string }>(
      "/provision/bucket",
      { companyUid },
    );
    return data;
  }

  // -- STS operations (VLT-8) -----------------------------------------------

  readonly sts = {
    /**
     * Vend task-scoped child credentials strictly narrower than the caller's
     * own membership. Backed by the vault-service `POST /sts/vend-child`
     * route (kebab-case to match the rest of the vault-service API).
     *
     * The child policy is intersected with the caller's membership on the
     * server — if `taskScope.allowedPrefixes` requests anything the parent
     * can't see, the server throws ScopeExceedsParentError before calling STS.
     *
     * Session name format: `${parentPersonUid}--task--${taskId}` — this lands
     * in CloudTrail verbatim, so every child S3 action can be traced back to
     * the parent task for incident response.
     */
    vendChild: async (input: VendChildInput): Promise<VendChildResult> => {
      const data = await this.post<VendChildResult>("/sts/vend-child", input);
      return data;
    },
  };

  // -- HTTP primitives with retry -------------------------------------------

  private async get<T>(path: string): Promise<T> {
    return this.request<T>("GET", path);
  }

  private async post<T>(path: string, body?: unknown): Promise<T> {
    return this.request<T>("POST", path, body);
  }

  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    let lastError: Error | undefined;

    for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
      if (attempt > 0) {
        const delay = BASE_DELAY_MS * Math.pow(2, attempt - 1);
        await sleep(delay);
      }

      const headers: Record<string, string> = {
        Authorization: `Bearer ${this.authToken}`,
        Accept: "application/json",
      };

      const init: RequestInit = { method, headers };

      if (body !== undefined) {
        headers["Content-Type"] = "application/json";
        init.body = JSON.stringify(body);
      }

      let res: Response;
      try {
        res = await fetch(`${this.apiUrl}${path}`, init);
      } catch (err) {
        lastError = err instanceof Error ? err : new Error(String(err));
        if (attempt < MAX_RETRIES) continue;
        throw lastError;
      }

      if (res.ok) {
        if (res.status === 204) return undefined as T;
        return (await res.json()) as T;
      }

      const responseBody = await res.text();

      // Non-retryable errors → throw immediately
      if (!isTransient(res.status)) {
        throw this.mapError(res.status, responseBody);
      }

      // Retryable — store and loop
      lastError = this.mapError(res.status, responseBody);
    }

    throw lastError ?? new VaultClientError("Request failed after retries", 500);
  }

  private mapError(status: number, body: string): VaultClientError {
    const message = this.extractMessage(body);

    switch (status) {
      case 401:
        return new VaultAuthError(message);
      case 403:
        return new VaultPermissionDeniedError(message);
      case 404:
        return new VaultNotFoundError(message);
      case 409:
        return new VaultConflictError(message);
      default:
        return new VaultClientError(message || `Request failed with status ${status}`, status, body);
    }
  }

  private extractMessage(body: string): string {
    try {
      const parsed = JSON.parse(body) as { message?: string; error?: string };
      return parsed.message ?? parsed.error ?? body;
    } catch {
      return body;
    }
  }
}
