#!/usr/bin/env bash
# deploy.sh — Deploy all HQ Cloud CDK stacks
#
# Outputs resource ARNs to .env.deployed for local dev use.
# Usage: ./deploy.sh [--profile hq-cloud]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$SCRIPT_DIR/../../worker-runtime/infra"
ENV_FILE="$SCRIPT_DIR/../../.env.deployed"

echo "=== HQ Cloud Deploy ==="
echo "Infra dir: $INFRA_DIR"
echo ""

# Deploy all stacks
cd "$INFRA_DIR"
npx cdk deploy --all --require-approval never --outputs-file "$ENV_FILE.json" "$@"

echo ""
echo "=== Extracting outputs ==="

# Parse CDK outputs JSON into .env format
if command -v node &>/dev/null && [ -f "$ENV_FILE.json" ]; then
  node -e "
    const fs = require('fs');
    const outputs = JSON.parse(fs.readFileSync('$ENV_FILE.json', 'utf8'));
    const lines = ['# HQ Cloud deployed resource ARNs', '# Auto-generated by deploy.sh', ''];
    for (const [stackName, stackOutputs] of Object.entries(outputs)) {
      lines.push('# ' + stackName);
      for (const [key, value] of Object.entries(stackOutputs)) {
        const envKey = key.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
        lines.push(envKey + '=' + value);
      }
      lines.push('');
    }
    fs.writeFileSync('$ENV_FILE', lines.join('\n'));
  "
  echo "Resource ARNs written to $ENV_FILE"
else
  echo "Warning: Could not parse outputs. Raw JSON at $ENV_FILE.json"
fi

echo ""
echo "=== Deploy Complete ==="
