/**
 * godClaw — task-scoped child credential vending (VLT-8 US-002).
 *
 * Thin wrapper over `VaultClient.sts.vendChild` for the goClaw manager side.
 *
 * The reason this exists as its own package (rather than just being a
 * VaultClient call inline in godClaw task code) is that godClaw tasks
 * need a stable import surface:
 *
 *   import { vendChildCredentials } from "@indigoai-us/godclaw";
 *
 * rather than reaching into hq-cloud internals. It also lets us layer on
 * godClaw-specific concerns (task ID generation, audit logging, telemetry)
 * without touching the shared VaultClient.
 *
 * Security note: the strict-subset invariant lives server-side in the
 * vault-service (scope-override.ts from VLT-8 US-001). This client-side
 * wrapper does NOT validate prefixes — a compromised godClaw calling this
 * directly can still only vend what its own membership allows. That's the
 * load-bearing property of VLT-8.
 */

import type {
  VaultClient,
  VendChildInput,
  VendChildResult,
  TaskScope,
} from "@indigoai-us/hq-cloud";

export interface GodclawTaskInput {
  /** Company UID the task runs against (e.g. `cmp_01HV...`). */
  companyUid: string;
  /** ULID generated by godClaw for this task. Used in the STS session name. */
  taskId: string;
  /**
   * Human-readable task description (<256 chars). Flows to the vault-service
   * audit log alongside the session.
   */
  taskDescription: string;
  /** What prefixes and actions the child is allowed to touch. */
  taskScope: TaskScope;
  /**
   * Optional — omit to let the server default to 900s (AWS STS AssumeRole
   * enforces a 900s floor; the task-scoped policy is the real security
   * boundary, not the duration).
   */
  durationSeconds?: number;
}

/** Result returned to the caller — ready to hand to `spawnChild`. */
export interface GodclawChildCredentials {
  accessKeyId: string;
  secretAccessKey: string;
  sessionToken: string;
  sessionName: string;
  expiresAt: string;
  /** Echoed for convenience so the caller can pass them to `spawnChild`. */
  taskId: string;
  companyUid: string;
}

/**
 * Vend task-scoped child credentials from the vault-service.
 *
 * Throws whatever the underlying VaultClient throws:
 *   - VaultAuthError (401) — godClaw session expired
 *   - VaultPermissionDeniedError (403) — taskScope exceeds parent
 *   - VaultClientError (429) — rate limit tripped
 *   - VaultClientError (500+) — server error (retried by VaultClient)
 */
export async function vendChildCredentials(
  vaultClient: VaultClient,
  task: GodclawTaskInput,
): Promise<GodclawChildCredentials> {
  if (!task.taskId) {
    throw new Error("vendChildCredentials: taskId is required");
  }
  if (task.taskDescription.length >= 256) {
    throw new Error(
      `vendChildCredentials: taskDescription must be <256 chars (got ${task.taskDescription.length})`,
    );
  }
  if (task.taskScope.allowedPrefixes.length === 0) {
    throw new Error("vendChildCredentials: taskScope.allowedPrefixes must not be empty");
  }

  const input: VendChildInput = {
    companyUid: task.companyUid,
    taskId: task.taskId,
    taskDescription: task.taskDescription,
    taskScope: task.taskScope,
    ...(task.durationSeconds !== undefined && { durationSeconds: task.durationSeconds }),
  };

  const result: VendChildResult = await vaultClient.sts.vendChild(input);

  return {
    accessKeyId: result.credentials.accessKeyId,
    secretAccessKey: result.credentials.secretAccessKey,
    sessionToken: result.credentials.sessionToken,
    sessionName: result.sessionName,
    expiresAt: result.expiresAt,
    taskId: task.taskId,
    companyUid: task.companyUid,
  };
}
