#!/usr/bin/env bash
#
# Auto-generate Codex skill wrappers for Claude Code commands that lack one.
# Each generated skill is a thin delegate — loads the original command file.
# Dedicated skills (with custom SKILL.md logic) are never overwritten.
#
# Usage:
#   scripts/sync-commands-to-skills.sh           # sync all
#   scripts/sync-commands-to-skills.sh --dry-run # preview without writing
#   scripts/sync-commands-to-skills.sh --force   # regenerate even if skill exists
#   scripts/sync-commands-to-skills.sh --clean   # remove auto-generated skills whose command was deleted
#
# Called automatically by: codex-skill-bridge.sh install

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HQ_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SKILLS_DIR="${HQ_ROOT}/.claude/skills"
COMMANDS_DIR="${HQ_ROOT}/.claude/commands"

DRY_RUN=false
FORCE=false
CLEAN=false

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    --force)   FORCE=true ;;
    --clean)   CLEAN=true ;;
    *)         echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

AUTO_MARKER="# auto-generated: command-skill-bridge"

to_title_case() {
  echo "$1" | tr '-' ' ' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1'
}

first_sentence() {
  echo "$1" | sed 's/\. .*/\./' | cut -c1-120
}

# Extract frontmatter field from a .md file
extract_field() {
  local file="$1"
  local field="$2"
  awk -v field="$field" '
    /^---$/ { fm++; next }
    fm == 1 && $0 ~ "^"field":" {
      sub("^"field":[ ]*", "")
      if ($0 ~ /^\|/) { multiline=1; next }
      gsub(/^["'\''"]|["'\''"]$/, "")
      print
      exit
    }
    fm == 1 && multiline && /^  / {
      sub(/^  /, "")
      printf "%s ", $0
      next
    }
    fm == 1 && multiline && !/^  / { exit }
  ' "$file" | sed 's/ $//'
}

# Check if a skill was auto-generated by this script
is_auto_generated() {
  local skill_dir="$1"
  local skill_md="${skill_dir}/SKILL.md"
  [ -f "$skill_md" ] && grep -q "$AUTO_MARKER" "$skill_md" 2>/dev/null
}

# ── Clean phase: remove orphaned auto-generated skills ──────────────────
if [ "$CLEAN" = true ]; then
  cleaned=0
  for skill_dir in "${SKILLS_DIR}"/*/; do
    [ -d "$skill_dir" ] || continue
    skill_name="$(basename "$skill_dir")"
    cmd_file="${COMMANDS_DIR}/${skill_name}.md"

    if is_auto_generated "$skill_dir" && [ ! -f "$cmd_file" ]; then
      if [ "$DRY_RUN" = true ]; then
        echo "Would remove orphan: $skill_name"
      else
        rm -rf "$skill_dir"
        echo "Removed orphan: $skill_name"
      fi
      cleaned=$((cleaned + 1))
    fi
  done
  echo "Cleaned: $cleaned orphaned skills"
  [ "$CLEAN" = true ] && [ "$FORCE" = false ] && exit 0
fi

# ── Sync phase: create skills for commands that lack one ────────────────
created=0
skipped_dedicated=0
skipped_exists=0
skipped_no_desc=0

for cmd_file in "${COMMANDS_DIR}"/*.md; do
  [ -f "$cmd_file" ] || continue

  cmd_name="$(basename "$cmd_file" .md)"
  skill_dir="${SKILLS_DIR}/${cmd_name}"

  # If a dedicated (non-auto-generated) skill exists, never touch it
  if [ -d "$skill_dir" ] && ! is_auto_generated "$skill_dir"; then
    skipped_dedicated=$((skipped_dedicated + 1))
    continue
  fi

  # If auto-generated skill exists and not --force, skip
  if [ -d "$skill_dir" ] && [ "$FORCE" = false ]; then
    skipped_exists=$((skipped_exists + 1))
    continue
  fi

  # Extract metadata from command frontmatter
  description="$(extract_field "$cmd_file" "description")"
  arg_hint="$(extract_field "$cmd_file" "argument-hint")"

  if [ -z "$description" ]; then
    skipped_no_desc=$((skipped_no_desc + 1))
    continue
  fi

  display_name="$(to_title_case "$cmd_name")"
  short_desc="$(first_sentence "$description")"

  # Build optional args block
  args_block=""
  if [ -n "$arg_hint" ]; then
    args_block="args:
  - name: input
    description: \"${arg_hint}\"
    required: false"
  fi

  if [ "$DRY_RUN" = true ]; then
    echo "Would create: $cmd_name"
    echo "  display_name: $display_name"
    echo "  description:  $short_desc"
    echo
    created=$((created + 1))
    continue
  fi

  mkdir -p "${skill_dir}/agents"

  # Write SKILL.md with auto-generated marker
  cat > "${skill_dir}/SKILL.md" <<SKILL_EOF
---
${AUTO_MARKER}
name: ${cmd_name}
description: |
  ${description}
user-invokable: true
${args_block}
---

Run the HQ \`/${cmd_name}\` command. This skill delegates to the full command implementation.

Load and execute the command file at \`.claude/commands/${cmd_name}.md\`, passing through any user arguments.
SKILL_EOF

  # Write agents/openai.yaml
  cat > "${skill_dir}/agents/openai.yaml" <<YAML_EOF
interface:
  display_name: "${display_name}"
  short_description: "${short_desc}"
YAML_EOF

  echo "Created: ${cmd_name}"
  created=$((created + 1))
done

echo
echo "Summary: ${created} created, ${skipped_dedicated} dedicated skills preserved, ${skipped_exists} already synced, ${skipped_no_desc} skipped (no description)"
